### ISSUE TITLE
Is it possible to work offline

### ISSUE THREAD

**Issue by CeidAbbas** [id1945/ngx-scanner-qrcode#18]
Is it possible to work offline with this repository without internet

**Comment by id1945** [comment]
@CeidAbbas  
It's totally impossible!

**Comment by CeidAbbas** [comment]
I think it's a weakness for this repository.
Don't think so?

**Comment by id1945** [comment]
@CeidAbbas 
Because the design core is run by WebAssembly, it needs the Internet. WebAssembly improves fast qrcode scanning so need to use it.

**Comment by sam-lex** [comment]
@id1945 hey, I have a noob question, does this depend on external server or something? Since the code provided is minified, I can't verify by myself. I'm not familiar with WebAssembly, but just wanted to make sure that my app will not break in the future.
If it depends on a 3rd party server (hopefully not), then it becomes unreliable.

I didn't see anything on the networks tab though, so I didn't quite understand why it doesn't work offline...

**Comment by id1945** [comment]
> @id1945 hey, I have a noob question, does this depend on external server or something? Since the code provided is minified, I can't verify by myself. I'm not familiar with WebAssembly, but just wanted to make sure that my app will not break in the future. If it depends on a 3rd party server (hopefully not), then it becomes unreliable.
> 
> I didn't see anything on the networks tab though, so I didn't quite understand why it doesn't work offline...

**Comment by CeidAbbas** [comment]
Thank you

**Comment by id1945** [comment]
```diff
+ Since version 1.2.6 it has been edited the above issue.
```
