### ISSUE TITLE
Does not work with small QR codes

### ISSUE THREAD

**Issue by maerni** [id1945/ngx-scanner-qrcode#34]
Hi

We wanted to use this library for scanning QR codes. We use version 1.4.1 because our application is written in Angular 13.

With "normal" QR codes it works fine.

But with very small QR codes it does not work.

How can we fix this? Is there any possibility to use a higher resolution oder something like that?

Thanks very much.

**Comment by id1945** [comment]
Hi @maerni 

You can try this way.
First you press the upload button on the web, then your phone will have the feature to take pictures with the camera instead of choosing an existing photo, with taking pictures you can easily adjust the zoom in - zoom out the camera. I think it will work fine on some devices.

**Comment by maerni** [comment]
@id1945 yes, that's right, I can zoom with the smartphone.

But the camera doesn't focus, so the QR code still can't be read. 

Tested with the newest Samsung Galaxy smartphone.

What can we do for that the camera does focus and recognize the QR code?

Thanks very much.

Best regards
Mike

**Comment by TomLBarden** [comment]
@maerni Did you find a solution to this issue? We're encountering the same thing on some (particularly Android) devices. iPhones seem to handle focus decently well.

**Comment by maerni** [comment]
@TomLBarden no, i didn't find a working solution yet.
